name: Deploy Portfolio
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Esto asegura que el bot pueda escribir en gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Inyectar Secretos en el HTML
        run: |
          # Usamos | como delimitador por si la API Key tiene caracteres raros
          sed -i "s|API_KEY_PLACEHOLDER|${{ secrets.MY_SHEETS_API_KEY }}|g" index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
